# Server configuration
server:
  port: 4503  # The port your Spring Boot application will run on

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventmanagement  # JDBC URL for connecting to the MySQL database
    username: Dhinesh       # DB username
    password: Dhinesh1@     # DB password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver (for MySQL 8 and above)

  jpa:
    hibernate:
      ddl-auto: update  # Auto-creates/updates DB schema based on entity classes (use 'none' or 'validate' in production)
    show-sql: true      # Print SQL queries in the console (for debugging and development)
    properties:
      hibernate:
        format_sql: true  # Pretty-print the SQL output in logs for better readability
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Hibernate dialect for MySQL 8 (influences SQL generation)

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

    cache:
      type: redis

  mail:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: QH8mgICYNoHNn5mQxjGyNAzTuLXMVcCi
            client-secret: z_NFuKkajiSNFBCBxvm2rFfXTPUVvb7_vBcGOAoQp5Q9Ff0WGBzK7YElylXZV4Yk
            scope: openid, profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/auth0"
        provider:
          auth0:
            issuer-uri: https://dev-rgysaoyckkee8mur.us.auth0.com/






